port: 8080

logger:
  level: INFO
  output: log/output.log
  backupCount: 30

mysql:
  host: xxx
  port: 3306
  user: root
  password: xxx
  db: material_resources
  max_connections: 100

google_drive:
  auth_method: oauth
  credentials_path: data/credentials.json
  scopes:
  - https://www.googleapis.com/auth/drive
  token_path: data/token.json