CONTENT_TYPE_JSON = 'application/json'
CONTENT_TYPE_HTML = 'text/html'
CONTENT_TYPE_PDF = 'application/pdf'
CONTENT_TYPE_PNG = 'image/png'
CONTENT_TYPE_AAC = 'audio/aac'
CONTENT_TYPE_MD = 'text/markdown'
